---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gregturn/8-jdk-with-redis

inputs:
- name: spring-data-redis-github

outputs:
- name: spring-data-redis-artifactory

caches:
- path: maven

run:
  path: spring-data-redis-github/ci/build.sh
